# Generated by Django 4.2.4 on 2023-09-03 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CropPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=60)),
                ('planting_method', models.CharField(choices=[('D', 'direct seeding'), ('T', 'transplanting')], max_length=1)),
                ('current_status', models.CharField(blank=True, choices=[('P', 'planned ⚪'), ('S', 'seedling house 🟡'), ('B', 'in bed 🟠'), ('H', 'harvestable 🟢'), ('T', 'terminated ⚫')], default="('P', 'planned ⚪')", max_length=1, null=True)),
                ('date_of_planting', models.DateField()),
                ('date_of_bed_preparation', models.DateField(blank=True, null=True)),
                ('date_of_preseeding', models.DateField(blank=True, null=True)),
                ('harvest_range_start_date', models.DateField(blank=True, null=True)),
                ('harvest_range_end_date', models.DateField(blank=True, null=True)),
                ('plating_distance_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('num_plants', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('amount_available_for_harvest', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('abandoned', models.BooleanField(default=False)),
                ('abandonded_date', models.DateField(blank=True, null=True)),
                ('abandonded_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, default='', max_length=60)),
                ('verbose_name', models.CharField(blank=True, max_length=60)),
                ('beds', models.ManyToManyField(blank=True, to='farm_management_app.bed')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('bed_length_meters', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bed_width_centimeters', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bed_area_meters_squared', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlantFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botanical_name', models.CharField(default='', max_length=60)),
                ('common_name', models.CharField(default='', max_length=60)),
                ('slug', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('due_date', models.DateField()),
                ('task_type', models.CharField(choices=[('D', 'direct seeding'), ('P', 'pre-seeding'), ('B', 'bed preparation'), ('T', 'transplant'), ('H', 'harvest'), ('E', 'terminate'), ('O', 'other')], max_length=1)),
                ('completed', models.BooleanField(default=False)),
                ('auto_created', models.BooleanField(default=False)),
                ('intended_amount_harvested', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actual_amount_harvested', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('beds', models.ManyToManyField(blank=True, to='farm_management_app.bed')),
                ('cropplan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.cropplan')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.location')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('botanical_name', models.CharField(default='', max_length=60)),
                ('alias_botanical_name', models.CharField(blank=True, max_length=100, null=True)),
                ('common_name', models.CharField(default='', max_length=60)),
                ('plant_type', models.CharField(choices=[('A', 'annual'), ('B', 'biannual'), ('P', 'perennial')], max_length=1)),
                ('plating_distance_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sowing_depth_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperture_germination', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('slug', models.CharField(blank=True, default='', max_length=60)),
                ('plant_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.plantfamily')),
            ],
        ),
        migrations.CreateModel(
            name='Cultivar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('varietal_name', models.CharField(blank=True, default='', max_length=100)),
                ('seed_supplier', models.CharField(blank=True, max_length=100)),
                ('plating_distance_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sowing_depth_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('num_seeds_per_meter', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('days_seeding_to_transplatning', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('harvest_days_to_maturity_min', models.PositiveSmallIntegerField()),
                ('harvest_days_to_maturity_max', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('slug', models.CharField(blank=True, default='', max_length=60)),
                ('species', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.species')),
            ],
        ),
        migrations.AddField(
            model_name='cropplan',
            name='cultivar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.cultivar'),
        ),
        migrations.AddField(
            model_name='cropplan',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.location'),
        ),
        migrations.AddField(
            model_name='bed',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.location'),
        ),
    ]
