# Generated by Django 4.2.3 on 2023-07-20 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlantFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species_name', models.CharField(max_length=60)),
                ('plant_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.plantfamily')),
            ],
        ),
        migrations.CreateModel(
            name='Cultivar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultivar_name', models.CharField(max_length=60)),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.species')),
            ],
        ),
    ]
