# Generated by Django 4.2.4 on 2023-10-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplan',
            name='num_rows',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='num_rows',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='num_rows',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
