# Generated by Django 4.2.3 on 2023-07-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0002_remove_cultivar_cultivar_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivar',
            name='abandoned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='plant_type',
            field=models.CharField(choices=[('P', 'perennial'), ('A', 'annual')], default=('P', 'perennial'), max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivar',
            name='varietal_name',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='species',
            name='varietal_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
