# Generated by Django 4.2.3 on 2023-07-20 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0003_cultivar_abandoned_cultivar_active_cultivar_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivar',
            name='varietal_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='species',
            name='varietal_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
