# Generated by Django 4.2.4 on 2023-10-24 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0003_cultivar_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropplan',
            old_name='amount_available_for_harvest',
            new_name='amount_available_for_harvest_kg',
        ),
        migrations.AddField(
            model_name='cropplan',
            name='use_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='image_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
