# Generated by Django 4.2.4 on 2023-10-24 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0004_rename_amount_available_for_harvest_cropplan_amount_available_for_harvest_kg_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivar',
            name='temperture_germination',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='species',
            name='days_seeding_to_transplatning',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
