# Generated by Django 4.2.3 on 2023-07-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0005_area_bed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='area',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.area'),
        ),
    ]
