# Generated by Django 4.2.3 on 2023-07-20 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0006_alter_bed_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Area',
            new_name='Location',
        ),
        migrations.RenameField(
            model_name='bed',
            old_name='area_square_meters',
            new_name='area_meters_squared',
        ),
        migrations.RenameField(
            model_name='bed',
            old_name='area',
            new_name='location',
        ),
    ]
