# Generated by Django 4.2.3 on 2023-07-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0007_rename_area_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='area_meters_squared',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8),
        ),
    ]
