# Generated by Django 4.2.3 on 2023-07-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0008_alter_bed_area_meters_squared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bed',
            name='area_meters_squared',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
