# Generated by Django 4.2.3 on 2023-07-20 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0009_alter_bed_area_meters_squared'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('plant_date', models.DateField()),
                ('harvest_start_date', models.DateField()),
                ('harvest_end_date', models.DateField()),
                ('transplant', models.BooleanField(default=False)),
                ('transplant_date', models.DateField()),
                ('distance_between_crops', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distance_deep', models.DecimalField(decimal_places=2, max_digits=5)),
                ('num_rows', models.PositiveSmallIntegerField()),
                ('num_per_meter', models.PositiveSmallIntegerField()),
                ('num_plants', models.PositiveSmallIntegerField()),
                ('temperture_germination', models.DecimalField(decimal_places=2, max_digits=5)),
                ('crop_type', models.CharField(choices=[('S1', 'seed'), ('S1', 'seedling')], max_length=2)),
                ('beds', models.ManyToManyField(to='farm_management_app.bed')),
                ('cultivars', models.ManyToManyField(to='farm_management_app.cultivar')),
            ],
        ),
    ]
