# Generated by Django 4.2.3 on 2023-07-20 12:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0010_cropplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropplan',
            old_name='harvest_end_date',
            new_name='harvest_offical_date',
        ),
        migrations.RenameField(
            model_name='cropplan',
            old_name='harvest_start_date',
            new_name='harvest_range_end_date',
        ),
        migrations.AddField(
            model_name='cropplan',
            name='harvest_range_start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivar',
            name='abandonded_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('bed', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.bed')),
                ('cultivars', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.cultivar')),
            ],
        ),
    ]
