# Generated by Django 4.2.3 on 2023-07-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0011_rename_harvest_end_date_cropplan_harvest_offical_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropplan',
            name='harvest_offical_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='abandonded_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
