# Generated by Django 4.2.3 on 2023-07-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0013_alter_cropplan_transplant_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='bed',
        ),
        migrations.AddField(
            model_name='task',
            name='beds',
            field=models.ManyToManyField(to='farm_management_app.bed'),
        ),
        migrations.RemoveField(
            model_name='task',
            name='cultivars',
        ),
        migrations.AddField(
            model_name='task',
            name='cultivars',
            field=models.ManyToManyField(to='farm_management_app.cultivar'),
        ),
    ]
