# Generated by Django 4.2.3 on 2023-07-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0016_rename_num_per_meter_cropplan_num_seeds_per_meter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropplan',
            name='temperture_germination',
        ),
    ]
