# Generated by Django 4.2.3 on 2023-07-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0017_remove_cropplan_temperture_germination'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivar',
            name='beds',
            field=models.ManyToManyField(blank=True, to='farm_management_app.bed'),
        ),
    ]
