# Generated by Django 4.2.3 on 2023-07-23 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0018_cultivar_beds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropplan',
            name='cultivars',
        ),
        migrations.AddField(
            model_name='cropplan',
            name='cultivar',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.cultivar'),
            preserve_default=False,
        ),
    ]
