# Generated by Django 4.2.3 on 2023-07-23 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0019_remove_cropplan_cultivars_cropplan_cultivar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cultivars',
        ),
        migrations.AddField(
            model_name='task',
            name='cultivar',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.cultivar'),
        ),
    ]
