# Generated by Django 4.2.3 on 2023-07-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0020_remove_task_cultivars_task_cultivar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivar',
            name='harvest_range_end_date',
        ),
        migrations.RemoveField(
            model_name='cultivar',
            name='harvest_range_start_date',
        ),
        migrations.AddField(
            model_name='cropplan',
            name='harvest_range_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropplan',
            name='harvest_range_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='harvest_days_to_maturity_min',
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
    ]
