# Generated by Django 4.2.3 on 2023-07-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0021_remove_cultivar_harvest_range_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivar',
            name='harvest_days_to_maturity_max',
            field=models.PositiveSmallIntegerField(default=30),
            preserve_default=False,
        ),
    ]
