# Generated by Django 4.2.3 on 2023-07-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0022_cultivar_harvest_days_to_maturity_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivar',
            name='slug',
            field=models.CharField(default='', max_length=60),
        ),
    ]
