# Generated by Django 4.2.3 on 2023-07-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0023_cultivar_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivar',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
