# Generated by Django 4.2.3 on 2023-07-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0024_alter_cultivar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantfamily',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='species',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
