# Generated by Django 4.2.3 on 2023-07-24 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0025_plantfamily_slug_species_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
