# Generated by Django 4.2.3 on 2023-07-24 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0026_location_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplan',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
