# Generated by Django 4.2.3 on 2023-07-24 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0027_cropplan_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bed',
            old_name='width_meters',
            new_name='width_centimeters',
        ),
    ]
