# Generated by Django 4.2.3 on 2023-07-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0028_rename_width_meters_bed_width_centimeters'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantfamily',
            name='common_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
