# Generated by Django 4.2.3 on 2023-07-24 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0029_plantfamily_common_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='species',
            name='varietal_name',
        ),
    ]
