# Generated by Django 4.2.3 on 2023-07-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0030_remove_species_varietal_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivar',
            name='abandonded_date',
        ),
        migrations.RemoveField(
            model_name='cultivar',
            name='abandoned',
        ),
        migrations.AddField(
            model_name='cropplan',
            name='abandonded_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cropplan',
            name='abandoned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='days_seeding_to_transplatning',
            field=models.PositiveSmallIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='plant_type',
            field=models.CharField(choices=[('P', 'perennial'), ('A', 'annual'), ('B', 'biannual')], max_length=1),
        ),
    ]
