# Generated by Django 4.2.3 on 2023-07-24 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0031_remove_cultivar_abandonded_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='length_meters',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='width_centimeters',
        ),
        migrations.AddField(
            model_name='location',
            name='bed_length_meters',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='bed_width_centimeters',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
    ]
