# Generated by Django 4.2.3 on 2023-07-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0032_remove_bed_length_meters_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropplan',
            old_name='plant_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='cropplan',
            name='crop_type',
        ),
        migrations.RemoveField(
            model_name='cropplan',
            name='distance_between_crops',
        ),
        migrations.RemoveField(
            model_name='cropplan',
            name='distance_deep',
        ),
        migrations.RemoveField(
            model_name='cropplan',
            name='is_harvested',
        ),
        migrations.RemoveField(
            model_name='cropplan',
            name='name',
        ),
        migrations.RemoveField(
            model_name='cropplan',
            name='num_rows',
        ),
        migrations.RemoveField(
            model_name='cropplan',
            name='num_seeds_per_meter',
        ),
        migrations.RemoveField(
            model_name='cropplan',
            name='transplant',
        ),
        migrations.AddField(
            model_name='cropplan',
            name='green_manure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cropplan',
            name='seeding_type',
            field=models.CharField(choices=[('S1', 'direct seeding'), ('S1', 'pre-seeding')], default=('S1', 'direct seeding'), max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivar',
            name='num_seeds_per_meter',
            field=models.PositiveSmallIntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivar',
            name='plating_distance_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cultivar',
            name='sowing_depth_cm',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='plating_distance_cm',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cropplan',
            name='beds',
            field=models.ManyToManyField(blank=True, to='farm_management_app.bed'),
        ),
        migrations.AlterField(
            model_name='cropplan',
            name='num_plants',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
