# Generated by Django 4.2.3 on 2023-07-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0033_rename_plant_date_cropplan_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropplan',
            name='harvest_offical_date',
        ),
        migrations.RemoveField(
            model_name='cropplan',
            name='is_planted',
        ),
        migrations.AddField(
            model_name='cropplan',
            name='current_status',
            field=models.CharField(choices=[('G', 'growing'), ('H', 'harvestable'), ('T', 'terminated')], default=('G', 'growing'), max_length=1),
            preserve_default=False,
        ),
    ]
