# Generated by Django 4.2.3 on 2023-07-24 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0034_remove_cropplan_harvest_offical_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='cultivar',
        ),
        migrations.AddField(
            model_name='task',
            name='actual_amount_harvested',
            field=models.PositiveSmallIntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='auto_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='cropplan',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.cropplan'),
        ),
        migrations.AddField(
            model_name='task',
            name='date_ready_to_harvest',
            field=models.DateField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='intended_amount_harvested',
            field=models.PositiveSmallIntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('S', 'seed'), ('T', 'transplant'), ('H', 'harvest'), ('T', 'terminate'), ('O', 'other')], default=('O', 'other'), max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cropplan',
            name='num_plants',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
