# Generated by Django 4.2.3 on 2023-07-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0036_remove_task_date_ready_to_harvest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual_amount_harvested',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='intended_amount_harvested',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
