# Generated by Django 4.2.3 on 2023-07-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0037_alter_task_actual_amount_harvested_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropplan',
            name='seeding_type',
            field=models.CharField(choices=[('S1', 'direct seeding'), ('S2', 'pre-seeding')], max_length=2),
        ),
    ]
