# Generated by Django 4.2.3 on 2023-07-25 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0038_alter_cropplan_seeding_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropplan',
            name='seeding_type',
        ),
        migrations.RemoveField(
            model_name='cultivar',
            name='temperture_germination',
        ),
        migrations.AddField(
            model_name='cropplan',
            name='planting_method',
            field=models.CharField(choices=[('S1', 'direct seeding'), ('S2', 'transplanting')], default=('S1', 'direct seeding'), max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='temperture_germination',
            field=models.DecimalField(blank=True, decimal_places=2, default=10, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cropplan',
            name='current_status',
            field=models.CharField(choices=[('S', 'seedling house'), ('B', 'in bed'), ('H', 'harvestable'), ('T', 'terminated')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='num_seeds_per_meter',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='plant_type',
            field=models.CharField(choices=[('A', 'annual'), ('B', 'biannual'), ('P', 'perennial')], max_length=1),
        ),
    ]
