# Generated by Django 4.2.3 on 2023-07-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0039_remove_cropplan_seeding_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplan',
            name='abandonded_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cropplan',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
