# Generated by Django 4.2.3 on 2023-07-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0040_cropplan_abandonded_reason_cropplan_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropplan',
            old_name='start_date',
            new_name='date_of_planting',
        ),
        migrations.RenameField(
            model_name='cropplan',
            old_name='transplant_date',
            new_name='date_of_preseeding',
        ),
        migrations.AddField(
            model_name='cropplan',
            name='plating_distance_cm',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cropplan',
            name='product_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='cultivar',
            name='seed_supplier',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='species',
            name='alias_botanical_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('D', 'direct seeding'), ('P', 'pre-seeding'), ('T', 'transplant'), ('H', 'harvest'), ('T', 'terminate'), ('O', 'other')], max_length=1),
        ),
    ]
