# Generated by Django 4.2.3 on 2023-07-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0041_rename_start_date_cropplan_date_of_planting_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropplan',
            name='planting_method',
            field=models.CharField(choices=[('P1', 'direct seeding'), ('P2', 'transplanting')], max_length=2),
        ),
    ]
