# Generated by Django 4.2.3 on 2023-07-25 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0042_alter_cropplan_planting_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='temperture_germination',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
