# Generated by Django 4.2.3 on 2023-07-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0044_alter_cultivar_num_seeds_per_meter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropplan',
            name='planting_method',
            field=models.CharField(choices=[('D', 'direct seeding'), ('P', 'transplanting')], max_length=1),
        ),
    ]
