# Generated by Django 4.2.3 on 2023-07-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0045_alter_cropplan_planting_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropplan',
            name='planting_method',
            field=models.CharField(choices=[('D', 'direct seeding'), ('T', 'transplanting')], max_length=1),
        ),
    ]
