# Generated by Django 4.2.3 on 2023-07-25 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0047_cropplan_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='cropplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm_management_app.cropplan'),
        ),
    ]
