# Generated by Django 4.2.3 on 2023-07-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0048_alter_task_cropplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplan',
            name='verbose_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
