# Generated by Django 4.2.3 on 2023-07-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0049_cropplan_verbose_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='bed_length_meters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='location',
            name='bed_width_centimeters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
