# Generated by Django 4.2.3 on 2023-07-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0054_alter_cropplan_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropplan',
            name='current_status',
            field=models.CharField(choices=[('S', 'seedling house 🟡'), ('B', 'in bed 🟠'), ('H', 'harvestable 🟢'), ('T', 'terminated ⚫')], max_length=1),
        ),
    ]
