# Generated by Django 4.2.3 on 2023-07-27 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0055_alter_cropplan_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivar',
            name='beds',
        ),
        migrations.AddField(
            model_name='cropplan',
            name='date_of_preparing_bed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='days_seeding_to_transplatning',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='sowing_depth_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='species',
            name='alias_botanical_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='species',
            name='plating_distance_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
