# Generated by Django 4.2.3 on 2023-07-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0056_remove_cultivar_beds_cropplan_date_of_preparing_bed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropplan',
            name='green_manure',
        ),
        migrations.AlterField(
            model_name='bed',
            name='area_meters_squared',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bed',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='bed_length_meters',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='bed_width_centimeters',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
