# Generated by Django 4.2.3 on 2023-07-27 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0057_remove_cropplan_green_manure_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropplan',
            old_name='date_of_preparing_bed',
            new_name='date_of_bed_preparation',
        ),
    ]
