# Generated by Django 4.2.3 on 2023-07-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0058_rename_date_of_preparing_bed_cropplan_date_of_bed_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('D', 'direct seeding'), ('P', 'pre-seeding'), ('B', 'bed preparation'), ('T', 'transplant'), ('H', 'harvest'), ('T', 'terminate'), ('O', 'other')], max_length=1),
        ),
    ]
