# Generated by Django 4.2.3 on 2023-07-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0060_task_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropplan',
            name='plating_distance_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='cultivar',
            name='sowing_depth_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
