# Generated by Django 4.2.3 on 2023-08-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0061_alter_cropplan_plating_distance_cm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cropplan',
            name='current_status',
            field=models.CharField(blank=True, choices=[('S', 'seedling house 🟡'), ('B', 'in bed 🟠'), ('H', 'harvestable 🟢'), ('T', 'terminated ⚫')], max_length=1, null=True),
        ),
    ]
