# Generated by Django 4.2.3 on 2023-08-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0062_alter_cropplan_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='alias_botanical_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='species',
            name='plating_distance_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
