# Generated by Django 4.2.3 on 2023-08-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0063_alter_species_alias_botanical_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivar',
            name='plating_distance_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
