# Generated by Django 4.2.3 on 2023-08-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0064_alter_cultivar_plating_distance_cm'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropplan',
            name='amount_available_for_harvest',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cropplan',
            name='current_status',
            field=models.CharField(blank=True, choices=[('P', 'planned ⚪'), ('S', 'seedling house 🟡'), ('B', 'in bed 🟠'), ('H', 'harvestable 🟢'), ('T', 'terminated ⚫')], default="('P', 'planned ⚪')", max_length=1, null=True),
        ),
    ]
