# Generated by Django 4.2.3 on 2023-08-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0065_cropplan_amount_available_for_harvest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bed',
            name='active',
        ),
        migrations.RemoveField(
            model_name='bed',
            name='area_meters_squared',
        ),
        migrations.AddField(
            model_name='location',
            name='bed_area_meters_squared',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
