# Generated by Django 4.2.3 on 2023-08-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm_management_app', '0066_remove_bed_active_remove_bed_area_meters_squared_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cultivar',
            name='plant_type',
        ),
        migrations.AddField(
            model_name='species',
            name='plant_type',
            field=models.CharField(choices=[('A', 'annual'), ('B', 'biannual'), ('P', 'perennial')], default=('A', 'annual'), max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='sowing_depth_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
